# Generated by Django 4.1.2 on 2022-10-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Prestation",
                "verbose_name_plural": "Prestations",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="FactureVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_de_facture", models.CharField(max_length=100, unique=True)),
                (
                    "type_de_facture",
                    models.CharField(
                        choices=[
                            ("FD", "Facture définitive"),
                            ("A", "Facture d'Acompte"),
                        ],
                        default="FD",
                        max_length=2,
                    ),
                ),
                ("date", models.DateField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mode_de_reglement",
                    models.CharField(
                        choices=[
                            ("ES", "Espèces"),
                            ("CH", "Chèque"),
                            ("VI", "Virement"),
                            ("CB", "Carte bancaire"),
                        ],
                        max_length=2,
                    ),
                ),
                ("date_du_reglement", models.DateField(blank=True, null=True)),
                (
                    "statut_de_paiement",
                    models.CharField(
                        choices=[
                            ("RE", "Reçu"),
                            ("EN", "En attente"),
                            ("AN", "Annulé"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                ("prestations", models.ManyToManyField(to="ventes.prestation")),
            ],
        ),
    ]
