# Generated by Django 4.1.2 on 2022-10-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturevente",
            name="document_lie",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/factures"
            ),
        ),
    ]
