# Generated by Django 3.2.16 on 2022-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_alter_facturevente_document_lie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturevente',
            name='type_de_facture',
            field=models.CharField(choices=[('FD', 'Facture définitive'), ('A', "Facture d'Acompte")], default='FD', help_text="Note : les factures d'acompte se font à la date de réception du paiement", max_length=2),
        ),
    ]
