# Generated by Django 4.1.2 on 2022-10-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[("A", "Adulte"), ("E", "Enfant")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                ("adresse", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="SessionPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session patient",
                "verbose_name_plural": "Sessions patient",
                "ordering": ["date"],
            },
        ),
    ]
