# Generated by Django 4.1.2 on 2022-10-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ventes", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionpatient",
            name="prestation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ventes.prestation"
            ),
        ),
    ]
